### ISSUE TITLE
.env.example file missing in repository

### ISSUE THREAD

**Issue by Slyracoon23** [homanp/langchain-ui-api#5]
**Description**:

The README file instructs users to duplicate `.env.example` to `.env` in order to set up the project, but the `.env.example` file is missing from the repository.

**Steps to reproduce:**

1. Clone the repository.
2. Look for the `.env.example` file in the root directory.

**Expected behavior:**

A `.env.example` file should be present in the root directory to serve as a template for setting up the environment variables.

**Actual behavior:**

The `.env.example` file is missing from the root directory.

**Possible solution:**

Please add a `.env.example` file to the repository with the necessary environment variables and their default values to help users set up the project correctly.

**Comment by homanp** [comment]
@Slyracoon23 
Add these depending in the database you are using. I'm currently migrating prisma from the front-end to back-end which will make all of this easier. Bare with me :)

```
SUPABASE_URL=
SUPABASE_KEY=
OPENAI_API_KEY=
```

**Comment by Slyracoon23** [comment]
@homanp 
I saw that there were some front-end environment variables as well as back-end environment variables.

I will wait for the PR then :)

Thanks

**Comment by homanp** [comment]
@Slyracoon23 yes, previously the backend was written in node but due to the lacking feature set of the Typscript version of Langchain I decided to migrate all backend related stuff to Python. First step wast the agents, next is document Q&A and the after that I will migrate the other back-end related stuff as well. 

This repo will in the future be the one of interest for people wanting to experiment or deploy their own agents. The other one will only be UI. 

I will try to finish this by tomorrow or Saturday.
